stages:
- name: docker build image
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
      registry: index.docker.io
- name: deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
notification: {}
